name: Go

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/linux/sbf main.go
        GOOS=windows GOARCH=amd64 go build -o build/windows/sbf.exe main.go
        GOOS=darwin GOARCH=amd64 go build -o build/macos/sbf main.go
    - name: Publish for Linux
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/linux/sbf
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Publish for Windows
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows/sbf.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Publish for macOS
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/macos/sbf
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
