name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/linux/sbf main.go
        GOOS=windows GOARCH=amd64 go build -o build/windows/sbf.exe main.go
        GOOS=darwin GOARCH=amd64 go build -o build/macos/sbf main.go
        ls -lh build/linux
        ls -lh build/windows
        ls -lh build/macos
